### ISSUE TITLE
supporting licenses on instrument level

### ISSUE THREAD

**Issue by ghost** [nfdi4health/mica-templates#2]
# Requirement
The user wants to have information about the license of an instrument. Therefore, a unique way to show the license is needed.

# Proposal
Currently, license information is only added in the description field. For better convenience, a license field can be added.
![fillout](https://user-images.githubusercontent.com/69628891/118612881-805a4180-b7be-11eb-9a6f-3234be105f09.png)

For the instrument browser, the license can be added as a button (linking to the license definition):
![show](https://user-images.githubusercontent.com/69628891/118613016-a1bb2d80-b7be-11eb-8fdf-213f6468fc15.png)
As long as no license is known, the field might be blank, and in such cases, the license button might not be displayed. Best would be to have the information `If you intend to reuse this instrument or parts of it in your study, please contact the authors to clarify copyright issues` in the description until a license has been defined.

**Comment by ghost** [comment]
by Carsten Schmidt:

> adding a field like this as part of the instruments description seems very useful to me.
> 
> It should be free text, to be able to provide additional information or, alternatively, one field with a standard selection of the licence model, and an additional explanatory field.

**Comment by s-aliaksandra** [comment]
@joerghenkebuero, taking into account Carsten's proposal, I would formulate the requirements as follows:

Add two new elements:
1. “Use rights”, where the following standard sentences will be displayed: 
1.a.	If a licence has been selected: “This work is licensed under [_full name of the licence_]. To view a copy of the licence, visit _http://creativecommons.org/licenses/[.....]_"
1.b.	Otherwise “If you intend to reuse this instrument or parts of it, please contact the authors to clarify copyright issues.”
1.b.i.	A small remark: In the statement, we refer to “authors”, but their contact information is not yet displayed on the instrument pages.
2. “Additional information on use rights”, where any additional information can be entered. The field should be displayed, only if some information has been entered.

For the full list of the currently used licences, see https://1drv.ms/x/s!AkyVMf3c0ldOsDzh-2-kw-nlNME8?e=xCqjS5

**Comment by joerghenkebuero** [comment]
regarding 1., I think such a solution might work:

```html
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<select onchange="$('#selected').html(this.value);">
<option value="This work is licensed under Creative Commons Attribution 4.0 International. to view a copy of the license, visit https://creativecommons.org/li
censes/by/4.0/">CC BY 4.0</option>
<option value="This work is licensed under Creative Commons Attribution Non Commercial 4.0 International. to view a copy of the license, visit https://creativ
ecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</option>
<option value="This work is licensed under Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO. to view a copy of the license, visit https://cr
eativecommons.org/licenses/by-nc-nd/3.0/igo/">CC BY-NC-ND-3.0 IGO</option>
<option value="This work is licensed under Creative Commons Attribution Non Commercial No Derivatives 4.0 International. to view a copy of the license, visit 
https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</option>                                                                                  
<option value="This work is licensed under Creative Commons Attribution Non Commercial Share Alike 4.0 International. to view a copy of the license, visit htt
ps://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</option>
<option value="This work is licensed under Creative Commons Attribution Non Commercial Share Alike 4.0 IGO. to view a copy of the license, visit https://creat
ivecommons.org/licenses/by-nc-sa/3.0/igo/">CC BY-NC-SA 3.0 IGO</option>
<option value="This work is licensed under Creative Commons Attribution No Derivatives 4.0 International. to view a copy of the license, visit https://creativ
ecommons.org/licenses/by-nd/4.0/">CC BY-ND 4.0</option>
<option value="This work is licensed under Creative Commons Attribution Share Alike 4.0 International. to view a copy of the license, visit https://creativeco
mmons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</option>
<option value="This work is licensed under Creative Commons Zero v1.0 Universal. to view a copy of the license, visit https://creativecommons.org/publicdomain
/zero/1.0/">CCO 1.0</option>
<option value="If you intend to reuse this instrument or parts of it please contact the authors to clarify copyright issues.">unknown</option>
</select>
<br />
Your choice:
<div id="selected" style="margin: 4px; padding: 4px; border: 1px solid red">

</div>
</body>
</html>
```
For a demonstration, please get in contact with me so that I can show you how that works.

**Comment by beanformer** [comment]
Only some comments:
- I wouldn't restrict the licenses to a subset. There are many licenses in the world, some are not open [https://www.openhealthhub.com/library/edinburgh-postnatal-depression-scale-epds/]. It's out of focus of this tools to be missionary.
- Maybe we populate from this: http://www.ebi.ac.uk/swo/SWO_0000002. The list should be available in the OLS from ZBMED.
- I know of no biometrician who can answer questions about licensing. We need to offer a webinar via TA4.

**Comment by ghost** [comment]
@s-aliaksandra and @joerghenkebuero discussed that issue and decided:

* not to propose all possible licenses, but add the ones that are needed currently (and extend whenever necessary)
* provide an option to add a license ID (e.g. CCO 1.0 or such) that can be filled out on instrument definition
* interpret that license ID on the template that shows the instrument content (e.g. here: https://mica.covid19.studyhub.nfdi4health.de/dataset/cils4covid ) in a new panel with the headline `License` that has the text `This work is licensed under Creative Commons Attribution Share Alike 4.0 International. To view a copy of the license, visit` , followed by the link to that license `https://creativecommons.org/licenses/by-sa/4.0/`
* add an additional field for `additional information on use rights` directly under the license in the same panel that does not show anything if no additional information was set

**Comment by ghost** [comment]
Examples of the upper proposal:

* for the license CC-BY-4.0, enhanced by an additional comment (Additional information on use rights):

![ccby4](https://user-images.githubusercontent.com/69628891/119164645-ed8b0280-ba5c-11eb-92b2-67b09bb1c4d8.png)

* for the lack of a license

![allrightsreserved](https://user-images.githubusercontent.com/69628891/119164655-efed5c80-ba5c-11eb-94f2-0f7625c477a8.png)

**Comment by ghost** [comment]
for the moment, because of lack of time, a simple text field for licenses is added only

**Comment by ghost** [comment]
the license field has been added as a simple text input field to the instrument editor in MICA and can be filled with known licenses. Default is the sentence

> Permission has been granted to display the instrument on this page. However, authors need to be contacted for their permission to reuse the instruments or parts of it.

as specified in the meeting from 2021-06-15 09:00.

**Comment by ghost** [comment]
added the display to the templates, so that the licenses can be seen now.

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/69628891/122221143-4bbad200-ceb1-11eb-9e8a-7ba5b6b98f5b.png)

In case of that error message, the instrument has not yet been republished with the new license field. Therefore, it is necessary to republish ALL instruments to add the new license field to the database. Even if the standard license text appears, the database does not yet know of it, so a republish is mandatory.

To do so, load the edit page for the instrument, save it and republish it:
![grafik](https://user-images.githubusercontent.com/69628891/122221587-b3711d00-ceb1-11eb-855c-626791dbda0f.png)

**Comment by ghost** [comment]
solved in a rudimentary way, so I close this for now (can be reopened whenever resources for a development are available)
